#!/bin/bash

# Get the root folder of our demo folder
ROOT_FOLDER=$(git rev-parse --show-toplevel)

# Load the common script
source $ROOT_FOLDER/_utils/common.sh

# Spin up the docker containers
source $ROOT_FOLDER/Labs/000-setup/01-init-servers.sh 2>&1 > /dev/null
source $ROOT_FOLDER/Labs/000-setup/02-init-ansible.sh 2>&1 > /dev/null

clear

# -------------------------------------------------------
# 1. Create the playbook
# -------------------------------------------------------
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 1] Creating lab016-files.yml playbook${COLOR_OFF}"
echo -e "${Green}* Covers: file (mkdir), copy, lineinfile, blockinfile, fetch${COLOR_OFF}"
docker exec ansible-controller sh -c "cat > /labs-scripts/lab016-files.yml << 'EOF'
---
- name: File Modules Demo
  hosts: all
  gather_facts: true
  vars:
    app_base: /opt/lab016
    env: lab

  tasks:
    # --- ansible.builtin.file - create directory tree ---
    - name: \"[file] Create application directory structure\"
      ansible.builtin.file:
        path: \"{{ app_base }}/{{ item }}\"
        state: directory
        mode: \"0755\"
      loop:
        - config
        - logs
        - data

    # --- ansible.builtin.copy - copy file with inline content ---
    - name: \"[copy] Deploy config file with inline content\"
      ansible.builtin.copy:
        content: |
          # App config for {{ inventory_hostname }}
          # Generated by Ansible
          [server]
          hostname = {{ inventory_hostname }}
          ip       = {{ ansible_default_ipv4.address }}
          env      = {{ env }}

          [logging]
          level    = info
          path     = {{ app_base }}/logs/app.log
        dest: \"{{ app_base }}/config/app.ini\"
        mode: \"0644\"

    # --- ansible.builtin.lineinfile - add a single line ---
    - name: \"[lineinfile] Ensure custom hosts entry exists in /etc/hosts\"
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: \"127.0.0.1 {{ inventory_hostname }}.lab.local\"
        regexp: \"^127\\.0\\.0\\.1 {{ inventory_hostname }}\\.lab\\.local\"
        state: present

    # --- ansible.builtin.blockinfile - add a block of text ---
    - name: \"[blockinfile] Add internal DNS entries block to /etc/hosts\"
      ansible.builtin.blockinfile:
        path: /etc/hosts
        marker: \"# {mark} ANSIBLE MANAGED BLOCK - lab016\"
        block: |
          10.0.0.10 web1.internal
          10.0.0.11 web2.internal
          10.0.0.20 db1.internal
        state: present

    # --- ansible.builtin.fetch - download file to controller ---
    - name: \"[fetch] Pull generated config back to controller\"
      ansible.builtin.fetch:
        src: \"{{ app_base }}/config/app.ini\"
        dest: \"/labs-scripts/fetched/\"
        flat: false
EOF"

echo -e "${GREEN}$ cat lab016-files.yml${COLOR_OFF}"
docker exec ansible-controller sh -c "cat /labs-scripts/lab016-files.yml"

# -------------------------------------------------------
# 2. Run the playbook
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 2] Running lab016-files.yml${COLOR_OFF}"
echo -e "${GREEN}$ ansible-playbook lab016-files.yml${COLOR_OFF}"
docker exec ansible-controller sh -c "cd /labs-scripts && ansible-playbook lab016-files.yml"

# -------------------------------------------------------
# 3. Verify results with ad-hoc commands
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 3] Verifying results with ad-hoc commands${COLOR_OFF}"

echo -e ""
echo -e "${CYAN}-- Verify directory structure was created --${COLOR_OFF}"
echo -e "${GREEN}$ ansible all -m command -a 'ls -la /opt/lab016/'${COLOR_OFF}"
docker exec ansible-controller sh -c "cd /labs-scripts && ansible all -m command -a 'ls -la /opt/lab016/'"

echo -e ""
echo -e "${CYAN}-- Read the deployed config file --${COLOR_OFF}"
echo -e "${GREEN}$ ansible all -m command -a 'cat /opt/lab016/config/app.ini'${COLOR_OFF}"
docker exec ansible-controller sh -c "cd /labs-scripts && ansible all -m command -a 'cat /opt/lab016/config/app.ini'"

echo -e ""
echo -e "${CYAN}-- Verify lineinfile entry was added --${COLOR_OFF}"
echo -e "${GREEN}$ ansible all -m shell -a 'grep lab.local /etc/hosts'${COLOR_OFF}"
docker exec ansible-controller sh -c "cd /labs-scripts && ansible all -m shell -a 'grep lab.local /etc/hosts'"

echo -e ""
echo -e "${CYAN}-- Verify blockinfile markers were inserted --${COLOR_OFF}"
echo -e "${GREEN}$ ansible all -m shell -a 'grep -A5 \"ANSIBLE MANAGED\" /etc/hosts'${COLOR_OFF}"
docker exec ansible-controller sh -c "cd /labs-scripts && ansible all -m shell -a 'grep -A5 \"ANSIBLE MANAGED\" /etc/hosts'"

echo -e ""
echo -e "${CYAN}-- Verify fetched files arrived on the controller --${COLOR_OFF}"
echo -e "${GREEN}$ ls -la /labs-scripts/fetched/${COLOR_OFF}"
docker exec ansible-controller sh -c "ls -la /labs-scripts/fetched/ 2>/dev/null || echo 'No fetched files found yet'"

# -------------------------------------------------------
# 4. Run again to demonstrate idempotency
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 4] Run again to confirm idempotency (should show all 'ok', changed=0)${COLOR_OFF}"
echo -e "${GREEN}$ ansible-playbook lab016-files.yml${COLOR_OFF}"
docker exec ansible-controller sh -c "cd /labs-scripts && ansible-playbook lab016-files.yml"

echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}Summary:${COLOR_OFF}"
echo -e "  ${Green}file        ${COLOR_OFF} → manage files, directories, symlinks (state: directory/touch/link/absent)"
echo -e "  ${Green}copy        ${COLOR_OFF} → transfer files or write inline content to remote hosts"
echo -e "  ${Green}lineinfile  ${COLOR_OFF} → idempotently ensure a single line exists (uses regexp)"
echo -e "  ${Green}blockinfile ${COLOR_OFF} → manage an entire block with auto-generated markers"
echo -e "  ${Green}fetch       ${COLOR_OFF} → pull files FROM managed hosts back to the controller"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
