#!/bin/bash

ROOT_FOLDER=$(git rev-parse --show-toplevel)
source $ROOT_FOLDER/_utils/common.sh
source $ROOT_FOLDER/Labs/000-setup/01-init-servers.sh 2>&1 > /dev/null
source $ROOT_FOLDER/Labs/000-setup/02-init-ansible.sh 2>&1 > /dev/null

clear

echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}Lab 035 - Cloud Modules (AWS / Azure)${COLOR_OFF}"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${Red}NOTE: Real cloud operations require AWS/Azure credentials (not available here).${COLOR_OFF}"
echo -e "${Red}      This demo shows patterns, config formats and a local cloud simulation.${COLOR_OFF}"

# -------------------------------------------------------
# 1. Install amazon.aws collection
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 1] Installing amazon.aws Galaxy collection${COLOR_OFF}"
echo -e "${GREEN}$ ansible-galaxy collection install amazon.aws${COLOR_OFF}"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
docker exec ansible-controller sh -c "ansible-galaxy collection install amazon.aws 2>&1 | tail -10 || true"

echo -e ""
echo -e "${CYAN}Installed cloud-related collections:${COLOR_OFF}"
docker exec ansible-controller sh -c "ansible-galaxy collection list 2>/dev/null | grep -E 'amazon|azure|google|cloud' || true"

# -------------------------------------------------------
# 2. Cloud simulation playbook - same patterns, no real cloud
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 2] Creating cloud simulation playbook (demonstrates patterns without cloud)${COLOR_OFF}"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
docker exec ansible-controller sh -c "cat > /labs-scripts/lab035-cloud-sim.yml << 'EOF'
---
- name: Lab 035 - Cloud Module Patterns (Simulation)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # These would come from aws_ec2 module in real usage
    ec2_instances:
      - name: web-server-01
        instance_type: t3.micro
        ami: ami-0c55b159cbfafe1f0
        subnet: subnet-prod-1a
        security_groups: [sg-web, sg-common]
        tags:
          Environment: production
          Role: webserver
          Team: platform

      - name: web-server-02
        instance_type: t3.micro
        ami: ami-0c55b159cbfafe1f0
        subnet: subnet-prod-1b
        security_groups: [sg-web, sg-common]
        tags:
          Environment: production
          Role: webserver
          Team: platform

      - name: db-primary-01
        instance_type: t3.large
        ami: ami-0c55b159cbfafe1f0
        subnet: subnet-prod-db
        security_groups: [sg-database, sg-common]
        tags:
          Environment: production
          Role: database
          Team: platform

    output_dir: /tmp/cloud-sim

  tasks:
    - name: Create output directory for simulation
      ansible.builtin.file:
        path: \"{{ output_dir }}\"
        state: directory
        mode: '0755'

    - name: Simulate launching EC2 instances (loop over definitions)
      ansible.builtin.debug:
        msg:
          - \"[SIMULATED] Would call: amazon.aws.ec2_instance\"
          - \"  name:          {{ item.name }}\"
          - \"  instance_type: {{ item.instance_type }}\"
          - \"  ami:           {{ item.ami }}\"
          - \"  subnet:        {{ item.subnet }}\"
          - \"  tags:          {{ item.tags | to_json }}\"
      loop: \"{{ ec2_instances }}\"
      loop_control:
        label: \"{{ item.name }}\"

    - name: Generate simulated inventory from instance definitions
      ansible.builtin.copy:
        dest: \"{{ output_dir }}/simulated-inventory.ini\"
        content: |
          # Simulated inventory (in production this is auto-generated by aws_ec2 dynamic inventory)
          [webservers]
          {% for inst in ec2_instances if inst.tags.Role == 'webserver' %}
          {{ inst.name }} ansible_host=10.0.1.{{ loop.index + 10 }} instance_type={{ inst.instance_type }}
          {% endfor %}

          [databases]
          {% for inst in ec2_instances if inst.tags.Role == 'database' %}
          {{ inst.name }} ansible_host=10.0.2.{{ loop.index + 10 }} instance_type={{ inst.instance_type }}
          {% endfor %}

          [production:children]
          webservers
          databases

          [production:vars]
          env=production
          ansible_user=ec2-user
        mode: '0644'

    - name: Show simulated inventory
      ansible.builtin.command: cat {{ output_dir }}/simulated-inventory.ini
      register: inv_content
      changed_when: false

    - name: Display generated inventory
      ansible.builtin.debug:
        msg: \"{{ inv_content.stdout_lines }}\"

    - name: Show instance count by role
      ansible.builtin.debug:
        msg:
          - \"Total instances:    {{ ec2_instances | length }}\"
          - \"Web servers:        {{ ec2_instances | selectattr('tags.Role', 'equalto', 'webserver') | list | length }}\"
          - \"Database servers:   {{ ec2_instances | selectattr('tags.Role', 'equalto', 'database') | list | length }}\"
EOF"

# -------------------------------------------------------
# 3. AWS EC2 dynamic inventory config
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 3] Creating AWS EC2 dynamic inventory configuration (aws_ec2.yml)${COLOR_OFF}"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
docker exec ansible-controller sh -c "cat > /labs-scripts/aws_ec2.yml << 'EOF'
# AWS EC2 Dynamic Inventory Plugin configuration
# Usage: ansible-inventory -i aws_ec2.yml --list
# Requires: amazon.aws collection + boto3 + valid AWS credentials

plugin: amazon.aws.aws_ec2

# AWS regions to query
regions:
  - us-east-1
  - eu-west-1

# Filter instances by tags (only managed instances)
filters:
  tag:ManagedBy: ansible
  instance-state-name: running

# How to name hosts in the inventory
hostnames:
  - tag:Name
  - private-ip-address

# Compose additional variables from EC2 metadata
compose:
  ansible_host: private_ip_address
  ec2_instance_type: instance_type
  ec2_region: placement.region

# Automatically create groups from EC2 tags
keyed_groups:
  - prefix: tag
    key: tags
  - prefix: region
    key: placement.region
  - prefix: type
    key: instance_type

# Cache dynamic inventory for 5 minutes
cache: true
cache_plugin: jsonfile
cache_timeout: 300
cache_connection: /tmp/aws_ec2_cache
EOF
echo '=== aws_ec2.yml (dynamic inventory config) ==='
cat /labs-scripts/aws_ec2.yml"

# -------------------------------------------------------
# 4. Show module documentation
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 4] Viewing amazon.aws.ec2_instance module documentation${COLOR_OFF}"
echo -e "${GREEN}$ ansible-doc amazon.aws.ec2_instance | head -30 || true${COLOR_OFF}"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
docker exec ansible-controller sh -c "ansible-doc amazon.aws.ec2_instance 2>/dev/null | head -30 || true"

echo -e ""
echo -e "${CYAN}Listing available amazon.aws modules:${COLOR_OFF}"
docker exec ansible-controller sh -c "ansible-doc -l 2>/dev/null | grep 'amazon.aws' | head -20 || true"

# -------------------------------------------------------
# 5. Run the simulation playbook
# -------------------------------------------------------
echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}[STEP 5] Running the cloud simulation playbook${COLOR_OFF}"
echo -e "${GREEN}$ ansible-playbook lab035-cloud-sim.yml${COLOR_OFF}"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
docker exec ansible-controller sh -c "cd /labs-scripts && ansible-playbook lab035-cloud-sim.yml"

echo -e ""
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
echo -e "${CYAN}Lab 035 complete!${COLOR_OFF}"
echo -e "  ${GREEN}amazon.aws collection${COLOR_OFF}     → ec2_instance, s3_bucket, iam_role, rds_instance, ..."
echo -e "  ${GREEN}aws_ec2.yml${COLOR_OFF}               → dynamic inventory auto-built from EC2 tags"
echo -e "  ${GREEN}keyed_groups${COLOR_OFF}              → automatic group creation from tags/attributes"
echo -e "  ${GREEN}loop over instance defs${COLOR_OFF}   → one task definition handles N instances"
echo -e "  ${GREEN}compose${COLOR_OFF}                   → map EC2 metadata to Ansible host variables"
echo -e "${YELLOW}-----------------------------------${COLOR_OFF}"
