#!/bin/bash
# =============================================================================
# Ansible Labs - Linux Server Entrypoint
#
# Waits for the ansible controller's SSH public key to appear in the shared
# volume, adds it to root's authorized_keys, then starts SSH daemon.
# =============================================================================
set -eu

SSH_SHARED=/ssh-shared
AUTHORIZED_KEYS=/root/.ssh/authorized_keys

mkdir -p /root/.ssh
chmod 700 /root/.ssh

# Wait for the controller's public key (generated by the ansible-labs container)
echo "Waiting for SSH public key from controller..."
for i in $(seq 1 30); do
  if [ -f "$SSH_SHARED/id_rsa.pub" ]; then
    break
  fi
  sleep 1
done

if [ -f "$SSH_SHARED/id_rsa.pub" ]; then
  cat "$SSH_SHARED/id_rsa.pub" >>"$AUTHORIZED_KEYS"
  sort -u "$AUTHORIZED_KEYS" -o "$AUTHORIZED_KEYS"
  chmod 600 "$AUTHORIZED_KEYS"
  echo "SSH public key installed for root."
else
  echo "Warning: controller public key not found after 30s, continuing anyway."
fi

# Configure sshd
mkdir -p /var/run/sshd
sed -i 's/#PermitRootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/#PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
echo "PubkeyAuthentication yes" >>/etc/ssh/sshd_config

# Generate RSA host key only (avoids ED25519 warning on controller side)
ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" 2>/dev/null || true
echo "HostKey /etc/ssh/ssh_host_rsa_key" >>/etc/ssh/sshd_config

# Start SSH daemon in foreground
exec /usr/sbin/sshd -D
