name: Lab-031.yaml

on:
  push:
    branches:
      - main
      - mkdocs
      - gh-pages
    paths:
      - "Labs/031-facts-deep-dive/**"
  pull_request:
    branches:
      - main
      - mkdocs
      - gh-pages
    paths:
      - "Labs/031-facts-deep-dive/**"

jobs:
  build:
    runs-on: ubuntu-latest
    # Execute the step demo to verify that all is working
    steps:
      # Check out the code
      - uses: actions/checkout@v5

      - name: Test Lab
        working-directory: Labs/031-facts-deep-dive
        run: bash ./_demo.sh
